In [23]:
import numpy as np
import pandas as pd

In [24]:
bi_2019_q1 = pd.read_csv('C:/Users/MyQuyen/Downloads/data_bicycle/Divvy_Trips_2019_Q1.csv')
bi_2020_q1 = pd.read_csv('C:/Users/MyQuyen/Downloads/data_bicycle/Divvy_Trips_2020_Q1.csv')

In [25]:
# đổi tên cho đồng nhất
bi_2019_q1 = bi_2019_q1.rename(columns={
    'trip_id': 'ride_id',
    'start_time': 'started_at',
    'end_time': 'ended_at',
    'from_station_name': 'start_station_name',
    'from_station_id': 'start_station_id',
    'to_station_name': 'end_station_name',
    'to_station_id': 'end_station_id',
    'usertype': 'member_casual'
})

In [26]:
# chuyển đổi format ride_id
bi_2019_q1['ride_id'] = bi_2019_q1['ride_id'].astype(str)

In [27]:
#  Xác định các cột chung xuất hiện ở TẤT CẢ các bảng
common_columns = [
    'ride_id', 'started_at', 'ended_at', 
    'start_station_name', 'start_station_id', 
    'end_station_name', 'end_station_id', 
    'member_casual', 'ride_length', 'day_of_week'
]

In [28]:
# Lọc các DataFrame chỉ lấy các cột chung này
bi_2019_q1_clean = bi_2019_q1[common_columns]
bi_2020_q1_clean = bi_2020_q1[common_columns]

In [29]:
# Gộp các bảng theo hàng dọc (Concatenate)
data = pd.concat([bi_2019_q1_clean, bi_2020_q1_clean], ignore_index=True)

In [30]:
data.head()

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_length,day_of_week
0,21742443,1/1/2019 0:04,1/1/2019 0:11,Wabash Ave & Grand Ave,199,Milwaukee Ave & Grand Ave,84.00,Subscriber,0:07:00,3
1,21742444,1/1/2019 0:08,1/1/2019 0:15,State St & Randolph St,44,Dearborn St & Van Buren St (*),624.00,Subscriber,0:07:00,3
2,21742445,1/1/2019 0:13,1/1/2019 0:27,Racine Ave & 18th St,15,Western Ave & Fillmore St (*),644.00,Subscriber,0:14:00,3
3,21742446,1/1/2019 0:13,1/1/2019 0:43,California Ave & Milwaukee Ave,123,Clark St & Elm St,176.00,Subscriber,0:30:00,3
4,21742447,1/1/2019 0:14,1/1/2019 0:20,Mies van der Rohe Way & Chicago Ave,173,Streeter Dr & Grand Ave,35.00,Subscriber,0:06:00,3

In [31]:
# chuẩn hóa cột member_casual 
data['member_casual'] = data['member_casual'].replace({'Subscriber': 'member', 'Customer': 'casual'})

In [32]:
data.head()

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_length,day_of_week
0,21742443,1/1/2019 0:04,1/1/2019 0:11,Wabash Ave & Grand Ave,199,Milwaukee Ave & Grand Ave,84.00,member,0:07:00,3
1,21742444,1/1/2019 0:08,1/1/2019 0:15,State St & Randolph St,44,Dearborn St & Van Buren St (*),624.00,member,0:07:00,3
2,21742445,1/1/2019 0:13,1/1/2019 0:27,Racine Ave & 18th St,15,Western Ave & Fillmore St (*),644.00,member,0:14:00,3
3,21742446,1/1/2019 0:13,1/1/2019 0:43,California Ave & Milwaukee Ave,123,Clark St & Elm St,176.00,member,0:30:00,3
4,21742447,1/1/2019 0:14,1/1/2019 0:20,Mies van der Rohe Way & Chicago Ave,173,Streeter Dr & Grand Ave,35.00,member,0:06:00,3

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791956 entries, 0 to 791955
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             791956 non-null  object
 1   started_at          791956 non-null  object
 2   ended_at            791956 non-null  object
 3   start_station_name  791956 non-null  object
 4   start_station_id    791956 non-null  int64
 5   end_station_name    791955 non-null  object
 6   end_station_id      791955 non-null  float64
 7   member_casual       791956 non-null  object
 8   ride_length         791956 non-null  object
 9   day_of_week         791956 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 60.4+ MB

In [34]:
## tìm giá trị mà ride_length < 0
# 1. Ép kiểu cột sang ride_length dạng Timedelta (Khoảng thời gian) 
data['ride_length'] = pd.to_timedelta(data['ride_length'], errors='coerce')

# 2. Chuyển đổi thành SỐ PHÚT (hoặc số giây bằng cách thay 'm' bằng 's') để dễ tính toán
data['ride_length'] = (data['ride_length'].dt.total_seconds() / 60).round(2)

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 791956 entries, 0 to 791955
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             791956 non-null  object
 1   started_at          791956 non-null  object
 2   ended_at            791956 non-null  object
 3   start_station_name  791956 non-null  object
 4   start_station_id    791956 non-null  int64
 5   end_station_name    791955 non-null  object
 6   end_station_id      791955 non-null  float64
 7   member_casual       791956 non-null  object
 8   ride_length         791931 non-null  float64
 9   day_of_week         791956 non-null  int64
dtypes: float64(2), int64(2), object(6)
memory usage: 60.4+ MB

In [67]:
## đếm giá trị mà ride_length < 0
(data['ride_length']<0).value_counts()

ride_length
False    791931
Name: count, dtype: int64

In [74]:
# Lọc lấy các chuyến đi hợp lệ từ 1 phút
data_clean = data[(data['ride_length'] >= 1) & (data['ride_length'] <= 1440)]

print(data_clean['ride_length'].describe())

count   785871.00
mean        14.14
std         36.60
min          1.00
25%          6.00
50%          9.00
75%         15.00
max       1438.00
Name: ride_length, dtype: float64

In [78]:
data_clean.head()

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_length,day_of_week,year
0,21742443,2019-01-01 00:04:00,1/1/2019 0:11,Wabash Ave & Grand Ave,199,Milwaukee Ave & Grand Ave,84.00,member,7.00,3,2019
1,21742444,2019-01-01 00:08:00,1/1/2019 0:15,State St & Randolph St,44,Dearborn St & Van Buren St (*),624.00,member,7.00,3,2019
2,21742445,2019-01-01 00:13:00,1/1/2019 0:27,Racine Ave & 18th St,15,Western Ave & Fillmore St (*),644.00,member,14.00,3,2019
3,21742446,2019-01-01 00:13:00,1/1/2019 0:43,California Ave & Milwaukee Ave,123,Clark St & Elm St,176.00,member,30.00,3,2019
4,21742447,2019-01-01 00:14:00,1/1/2019 0:20,Mies van der Rohe Way & Chicago Ave,173,Streeter Dr & Grand Ave,35.00,member,6.00,3,2019

In [81]:
# Tính trung bình (mean) của thời gian đi xe (ride_length)
data_clean = data[(data['ride_length'] >= 1) & (data['ride_length'] <= 1440)].copy()

data_clean['started_at'] = pd.to_datetime(data_clean['started_at'])
data_clean['year'] = data_clean['started_at'].dt.year

# Tính lại mean
print(data_clean.groupby('year')['ride_length'].mean())

year
2019   13.12
2020   15.02
Name: ride_length, dtype: float64

In [40]:
# Tính tổng số chuyến, trung bình, trung vị, max, min của từng nhóm
print(data_clean.groupby('member_casual')['ride_length'].agg(['count', 'mean', 'median', 'max']))

                count  mean  median     max
member_casual
casual          67957 41.26   23.00 1438.00
member         717914 11.57    8.00 1433.00

In [41]:
# Tính thời gian đi xe trung bình của 2 nhóm theo từng ngày trong tuần
print(data_clean.groupby(['member_casual', 'day_of_week'])['ride_length'].mean())

# Đếm tổng số chuyến đi của 2 nhóm theo từng ngày trong tuần
print(data_clean.groupby(['member_casual', 'day_of_week'])['ride_id'].count())

member_casual  day_of_week
casual         1             42.10
               2             46.20
               3             38.67
               4             44.48
               5             38.65
               6             38.66
               7             40.49
member         1             13.56
               2             11.08
               3             11.35
               4             11.42
               5             11.19
               6             11.18
               7             12.79
Name: ride_length, dtype: float64
member_casual  day_of_week
casual         1               18618
               2                5728
               3                7349
               4                7689
               5                7160
               6                7989
               7               13424
member         1               59995
               2              110068
               3              127558
               4              121553
               5              124784
               6              114796
               7               59160
Name: ride_id, dtype: int64

In [83]:
data_clean.to_csv('cyclistic_summary_by_day.csv', index=False)
print("Đã xuất file summary thành công!")

Đã xuất file summary thành công!

In [51]:
!pip install mysql-connector-python pandas

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pandas in c:\users\myquyen\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\myquyen\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\myquyen\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\myquyen\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\myquyen\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\myquyen\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
    --------------------------------------- 0.3/17.7 MB ? eta -:--:--
   -- ------------------------------------- 1.0/17.7 MB 3.5 MB/s eta 0:00:05
   --- ------------------------------------ 1.6/17.7 MB 3.1 MB/s eta 0:00:06
   ----- ---------------------------------- 2.4/17.7 MB 3.2 MB/s eta 0:00:05
   ------ --------------------------------- 2.9/17.7 MB 3.1 MB/s eta 0:00:05
   ------- -------------------------------- 3.1/17.7 MB 3.2 MB/s eta 0:00:05
   -------- ------------------------------- 3.7/17.7 MB 2.8 MB/s eta 0:00:06
   --------- ------------------------------ 4.2/17.7 MB 2.6 MB/s eta 0:00:06
   ---------- ----------------------------- 4.7/17.7 MB 2.7 MB/s eta 0:00:05
   ----------- ---------------------------- 5.2/17.7 MB 2.7 MB/s eta 0:00:05
   ------------- -------------------------- 6.0/17.7 MB 2.8 MB/s eta 0:00:05
   -------------- ------------------------- 6.6/17.7 MB 2.7 MB/s eta 0:00:05
   --------------- ------------------------ 6.8/17.7 MB 2.7 MB/s eta 0:00:05
   --------------- ------------------------ 6.8/17.7 MB 2.7 MB/s eta 0:00:05
   ---------------- ----------------------- 7.1/17.7 MB 2.5 MB/s eta 0:00:05
   ---------------- ----------------------- 7.3/17.7 MB 2.3 MB/s eta 0:00:05
   ----------------- ---------------------- 7.6/17.7 MB 2.2 MB/s eta 0:00:05
   ----------------- ---------------------- 7.9/17.7 MB 2.1 MB/s eta 0:00:05
   ------------------ --------------------- 8.1/17.7 MB 2.1 MB/s eta 0:00:05
   ------------------ --------------------- 8.4/17.7 MB 2.1 MB/s eta 0:00:05
   -------------------- ------------------- 8.9/17.7 MB 2.1 MB/s eta 0:00:05
   -------------------- ------------------- 9.2/17.7 MB 2.1 MB/s eta 0:00:05
   --------------------- ------------------ 9.7/17.7 MB 2.1 MB/s eta 0:00:04
   ----------------------- ---------------- 10.5/17.7 MB 2.1 MB/s eta 0:00:04
   ------------------------ --------------- 11.0/17.7 MB 2.1 MB/s eta 0:00:04
   ------------------------- -------------- 11.3/17.7 MB 2.1 MB/s eta 0:00:04
   -------------------------- ------------- 11.5/17.7 MB 2.1 MB/s eta 0:00:03
   -------------------------- ------------- 11.8/17.7 MB 2.1 MB/s eta 0:00:03
   ---------------------------- ----------- 12.6/17.7 MB 2.1 MB/s eta 0:00:03
   ----------------------------- ---------- 12.8/17.7 MB 2.1 MB/s eta 0:00:03
   ------------------------------ --------- 13.6/17.7 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 14.4/17.7 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 14.9/17.7 MB 2.2 MB/s eta 0:00:02
   ---------------------------------- ----- 15.5/17.7 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 16.5/17.7 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 2.3 MB/s  0:00:07
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

In [82]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "myquyen299"
host = "localhost"
port = "3306"
database = "data_bicycle"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "total_data"   # choose any table name
data_clean.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM total_data LIMIT 5;", engine)

,ride_id,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,member_casual,ride_length,day_of_week,year
0,21742443,2019-01-01 00:04:00,1/1/2019 0:11,Wabash Ave & Grand Ave,199,Milwaukee Ave & Grand Ave,84.00,member,7.00,3,2019
1,21742444,2019-01-01 00:08:00,1/1/2019 0:15,State St & Randolph St,44,Dearborn St & Van Buren St (*),624.00,member,7.00,3,2019
2,21742445,2019-01-01 00:13:00,1/1/2019 0:27,Racine Ave & 18th St,15,Western Ave & Fillmore St (*),644.00,member,14.00,3,2019
3,21742446,2019-01-01 00:13:00,1/1/2019 0:43,California Ave & Milwaukee Ave,123,Clark St & Elm St,176.00,member,30.00,3,2019
4,21742447,2019-01-01 00:14:00,1/1/2019 0:20,Mies van der Rohe Way & Chicago Ave,173,Streeter Dr & Grand Ave,35.00,member,6.00,3,2019